name: API Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Instalar Playwright
        run: npx playwright install

      - name: Rodar Smoke Tests no ambiente de teste
        env:
          PS_EMPRESA_URL: https://ps-empresa.onrender.com
        run: npm run playwright test --project=ps_empresa

      - name: Salvar relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
